name: musily_player
description: "A new Flutter project."
publish_to: 'none'
version: 2.0.4

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  audio_service: ^0.18.15
  audio_service_mpris: ^0.1.5
  just_audio: ^0.9.39
  just_audio_media_kit:
    git:
      url: https://github.com/MusilyApp/just_audio_media_kit.git
  media_kit_libs_linux: any
  media_kit_libs_windows_audio: any
  media_kit_libs_android_audio: any
  media_kit_libs_audio: ^1.0.4
  audio_session: ^0.1.21
  rxdart: ^0.27.7
  youtube_explode_dart: ^2.2.1
  http: ^1.2.2
  loading_animation_widget: ^1.2.1
  dio: ^5.5.0+1
  queue: ^3.1.0+2
  flutter_download_manager: ^0.5.5
  path_provider: ^2.1.4
  crypto: ^3.0.3
  shared_preferences: ^2.3.1
  path: ^1.9.0
  percent_indicator: ^4.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true
