on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: main
        required: true

name: Build Apk

env:
  PROPERTIES_PATH: "./android/key.properties"
  KEY_PATH: "./android/app/key.jks"

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract Version
        id: extract_version
        run: |
          version=$(grep 'version:' "pubspec.yaml" | awk '{print $2}' | awk -F'+' '{print $1}')
          echo "version=$version" >> $GITHUB_ENV
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17.x"

      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          flutter-version: 3.22.3

      
      
      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build universal APK
        run: flutter build apk --release

      - name: Release universal APK
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: FelipeYslaoker/musily_player
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-release.apk
          asset_name: musily_player-${{steps.extract_version.outputs.version}}.apk
          target_commit: main
          tag: ${{steps.extract_version.outputs.version}}
          prerelease: false
          overwrite: true